# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\torders.v1\"3\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08priority\x18\x03 \x01(\x05\"\x1d\n\x0fGetOrderRequest\x12\n\n\x02id\x18\x01 \x01(\t\"3\n\x10GetOrderResponse\x12\x1f\n\x05order\x18\x01 \x01(\x0b\x32\x10.orders.v1.Order\"4\n\x12\x43reateOrderRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\"6\n\x13\x43reateOrderResponse\x12\x1f\n\x05order\x18\x01 \x01(\x0b\x32\x10.orders.v1.Order\"$\n\x13StreamOrdersRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x32\xe6\x01\n\rOrdersService\x12\x43\n\x08GetOrder\x12\x1a.orders.v1.GetOrderRequest\x1a\x1b.orders.v1.GetOrderResponse\x12L\n\x0b\x43reateOrder\x12\x1d.orders.v1.CreateOrderRequest\x1a\x1e.orders.v1.CreateOrderResponse\x12\x42\n\x0cStreamOrders\x12\x1e.orders.v1.StreamOrdersRequest\x1a\x10.orders.v1.Order0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=28
  _globals['_ORDER']._serialized_end=79
  _globals['_GETORDERREQUEST']._serialized_start=81
  _globals['_GETORDERREQUEST']._serialized_end=110
  _globals['_GETORDERRESPONSE']._serialized_start=112
  _globals['_GETORDERRESPONSE']._serialized_end=163
  _globals['_CREATEORDERREQUEST']._serialized_start=165
  _globals['_CREATEORDERREQUEST']._serialized_end=217
  _globals['_CREATEORDERRESPONSE']._serialized_start=219
  _globals['_CREATEORDERRESPONSE']._serialized_end=273
  _globals['_STREAMORDERSREQUEST']._serialized_start=275
  _globals['_STREAMORDERSREQUEST']._serialized_end=311
  _globals['_ORDERSSERVICE']._serialized_start=314
  _globals['_ORDERSSERVICE']._serialized_end=544
# @@protoc_insertion_point(module_scope)
