apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoices-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: invoices-app
  template:
    metadata:
      labels:
        app: invoices-app
    spec:
      containers:
      - name: invoices-container
        image: invoices-svc-s13:latest
        ports:
        - containerPort: 8228
---
apiVersion: v1
kind: Service
metadata:
  name: invoices-svc-s13
spec:
  selector:
    app: invoices-app
  ports:
    - protocol: TCP
      port: 8228
      targetPort: 8228
