# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0cshipments.v1\"6\n\x08Shipment\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08tracking\x18\x03 \x01(\t\" \n\x12GetShipmentRequest\x12\n\n\x02id\x18\x01 \x01(\t\"?\n\x13GetShipmentResponse\x12(\n\x08shipment\x18\x01 \x01(\x0b\x32\x16.shipments.v1.Shipment\"7\n\x15\x43reateShipmentRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08tracking\x18\x02 \x01(\t\"B\n\x16\x43reateShipmentResponse\x12(\n\x08shipment\x18\x01 \x01(\x0b\x32\x16.shipments.v1.Shipment2\xc3\x01\n\x10ShipmentsService\x12R\n\x0bGetShipment\x12 .shipments.v1.GetShipmentRequest\x1a!.shipments.v1.GetShipmentResponse\x12[\n\x0e\x43reateShipment\x12#.shipments.v1.CreateShipmentRequest\x1a$.shipments.v1.CreateShipmentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHIPMENT']._serialized_start=31
  _globals['_SHIPMENT']._serialized_end=85
  _globals['_GETSHIPMENTREQUEST']._serialized_start=87
  _globals['_GETSHIPMENTREQUEST']._serialized_end=119
  _globals['_GETSHIPMENTRESPONSE']._serialized_start=121
  _globals['_GETSHIPMENTRESPONSE']._serialized_end=184
  _globals['_CREATESHIPMENTREQUEST']._serialized_start=186
  _globals['_CREATESHIPMENTREQUEST']._serialized_end=241
  _globals['_CREATESHIPMENTRESPONSE']._serialized_start=243
  _globals['_CREATESHIPMENTRESPONSE']._serialized_end=309
  _globals['_SHIPMENTSSERVICE']._serialized_start=312
  _globals['_SHIPMENTSSERVICE']._serialized_end=507
# @@protoc_insertion_point(module_scope)
