services:
  invoices-svc-s13:
    build:
      context: .
      dockerfile: invoices_svc.Dockerfile
    ports:
      - "8228:8228"

  gateway:
    build:
      context: .
      dockerfile: gateway.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - invoices-svc-s13
